name: Full Compile Check

on: [workflow_dispatch]

jobs:
  full-compile-check:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux/GCC (ancient), os: ubuntu-20.04, extraflags: "--system-sdl" }
          - { name: Linux/GCC, os: ubuntu-22.04, extraflags: "--system-sdl" }
          - { name: Linux/Clang, os: ubuntu-22.04, extraflags: "--system-sdl", prefix: "CC=clang CXX=clang++"}
          - { name: Windows/VS2022, os: windows-2022, extraflags: "-G 'Visual Studio 17 2022'" }
          - { name: Mac, os: macos-11 }

    steps:
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev

      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          
      - run: ${{matrix.platform.prefix}} python3 build.py --dependencies --configure --build ${{matrix.platform.extraflags}}
