name: Full Compile Check

on: [push, workflow_dispatch]

jobs:
  full-compile-check:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux/GCC (ancient), os: ubuntu-18.04, extraflags: "--system-sdl" }
          - { name: Linux/GCC, os: ubuntu-latest, extraflags: "--system-sdl" }
          - { name: Linux/Clang, os: ubuntu-latest, extraflags: "--system-sdl" }
          - { name: Windows/VS2022, os: windows-2022, extraflags: "-G 'Visual Studio 17 2022'" }
          - { name: Windows/VS2019, os: windows-2019, extraflags: "-G 'Visual Studio 16 2019'" }
          - { name: Mac, os: macos-11 }

    steps:
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - run: python3 build.py --dependencies --configure --build ${{ matrix.platform.extraflags }}
