name: Quick Compile Check

on: [workflow_dispatch]

jobs:
  quick-compile-check:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: Linux/GCC, os: ubuntu-latest, extraflags: "--system-sdl" }
          - { name: Windows/VS2022, os: windows-2022 }

    steps:
      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libsdl2-dev

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - run: python3 build.py --dependencies --configure --build ${{ matrix.platform.extraflags }}
